version: '3'

services:
  mysql:
    image: mysql:latest
    volumes:
      - ./mysql/db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  nodejs:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "4000:4000"
  
  crawler:
    build:
      context: .
      dockerfile: ./crawler/Dockerfile
    ports:
      - "5000:5000"
