version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - ./mysql/db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234

  nodejs:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "4000:4000"
    links:
      - mysql:mysql
    depends_on:
      - mysql
  
  crawler:
    build:
      context: .
      dockerfile: ./crawler/Dockerfile
    ports:
      - "5000:5000"
    links:
      - mysql:mysql
    depends_on:
      - mysql
